services:
  db: 
    image: mysql:8.0.37
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_USER: docker 
      MYSQL_PASSWORD: mysql
      MYSQL_DATABASE: rest_with_spring_boot_erudio
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3308
    ports:
      - 3308:3308
    expose:
      - 3308
    networks:
      - pedro-network

  rest-with-spring-boot:
    image: p12547254103/rest-with-spring-boot
    restart: always
    build: ./api-gateway
    working_dir: /api-gateway
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:mysql://db:3308/rest_with_spring_boot_erudio?useTimezone=true&serverTimezone=UTC
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: mysql
    ports:
      - 80:80
    command: mvn spring-boot:run
    depends_on:
      - db
    networks:
      - pedro-network

networks:
  pedro-network:
    driver: bridge
 